In [2]:
import pandas as pd

In [10]:
df = pd.read_excel (r"C:\Users\Padka\OneDrive\Desktop\Learning Python\Customer Call List.xlsx")
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [ ]:
# Delete duplicate rows

df.drop_duplicates(inplace=True)
df

In [ ]:
# Delete a useless column

df.drop(columns = "Not_Useful_Column", inplace=True)
df

In [ ]:
# Strip unwanted characters from the "Last_Name" column

# df["Last_Name"] = df["Last_Name"].str.lstrip("...")
# df["Last_Name"] = df["Last_Name"].str.lstrip("/")
# df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df

In [ ]:
# Strip unwanted characters from the "Phone_Number" column and format it as XXX-XXX-XXXX

# df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','',regex=True)
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
# df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df

In [ ]:
# Split the "Address" column into three new columns: "Street Address", "State", and "Zip_code"

df[["Street Address","State","Zip_code"]] = df["Address"].str.split(',', n=2, expand=True)
df

In [ ]:
# Replace "Yes" with "Y" and "No" with "N" in the "Paying Customer" column

df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

In [ ]:
# Replace "Yes" with "Y" and "No" with "N" in the "Do_Not_Contact" column

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df["Do_Not_Contact"]

In [ ]:
# Replace "N/a" and "NaN" with an empty string in the entire DataFrame

# df = df.replace('N/a','')
# df = df.replace('NaN','')
df = df.fillna('')
df

In [ ]:
# Delete rows where the "Do_Not_Contact" column has a value of "Y"

for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace = True)
df

In [ ]:
# Delete rows where the "Phone_Number" column has an empty string as a value

for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace = True)
df

# df.dropna(subset = "Phone_Number",inplace = True)

In [29]:
# Delete the "Address" column since we have already split it into three new columns

df = df.drop(columns= "Address")

In [30]:
# Reset the index of the DataFrame after deleting rows

df = df.reset_index(drop=True)
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,